### ISSUE TITLE
Simple-Peer devDependency tries to compile wrtc as optionalDependency

### ISSUE THREAD

**Issue by guymguym** [node-webrtc/node-webrtc#194]
I added the devDependency on simple-peer in bwtest as it really simplifies flow for small tests and such.

But now @feross added simple-peer an [optionalDependency](https://docs.npmjs.com/files/package.json#optionaldependencies) back on node-webrtc :) https://github.com/feross/simple-peer/commit/319a862d425965838b2501e2421e97f4aca8f5b2

So now when building wrtc, the devDependency on simple-peer is causing it to install, and then it attempts to install it's optional dependency on wrtc which is ridiculous when we actually in developer mode of wrtc.

The only solution I think of if in simple-peer the dependency would be devDependency, but there is not npm support for devOptionalDependency, so not sure how to fix. Ideas?

**Comment by modeswitch** [comment]
Oh, that might explain why `wrtc` built twice for me. I hope we can find a fix for that!

**Comment by rosskukulinski** [comment]
```
09:54 othiym23: rossk: I mean, simple-peer should clearly only be installing once, but that's a specific incidence of a general pattern, which is that things that are clear from observation are surprisingly hard to implement in the current npm installer
09:54 othiym23: rossk: which is why iarna wrote a new one, but it's not released yet ;)
09:55 rossk: :)
09:55 othiym23: optionalDevDeps feel like a bridge too far for me, btw
09:55 othiym23: we're creating this combinatorial explosion of dependency types and combinations that's very difficult to reason about and that creates a lot of opportunities for edge cases
09:55 rossk: yes -- and in this case its more complex because its a circular dep
```

**Comment by guymguym** [comment]
@rosskukulinski no doubt, dependency systems are hard. this field is always in such a mess that more systems and package managers just keep popping up trying to make things right :) I find it very similar to managing objects and references in shared-memory - you just got to do it because copying is not an option, but it's a real pain - maintaining refs, ref-counts, weak-refs, circular-refs...

anyway, for now I fixated the dependency on simple-peer's version (in #195) to 4.0.4 which is before the circular dependency was added, so at least until a version update is required this should be fine.

**Comment by feross** [comment]
Sorry for complicating your lives, hehe. Obviously making `simple-peer` work out-of-the-box in node is really handy to lots of people. And it's only possible due to your great work here :-)

I think using version 4.0.4 makes total sense. But, wanted to share another option I thought of, should you want the latest version at some point in the future. You could remove the `simple-peer` dep and add an npm "install" script (runs automatically on `npm install`) which just executes `npm install simple-peer --no-optional`. This will skip installing `wrtc` since it's an optional dep.

**Comment by guymguym** [comment]
@feross Thanks, But notice that the "install" script of wrtc is called even when it is installed as a dependency, so it would still be called when installing simple-peer or packages that use it - which is probably not really circular, but still installs simple-peer twice...

So I tried to add a condition to figure out if dev mode using env variables `npm_package_name` and `npm_config_dev` here https://github.com/guymguym/node-webrtc/commit/674606e62fad89cbdde49431dbca41e6462db107#diff-e1520c01790bdbcdc10e9f8eeb964f0eR3 and I hope this condition is correct.

**Comment by feross** [comment]
Hey guys, just wanted to let you know that the latest version of `simple-peer`, v5.0.0, makes `wrtc` a `devDependency` instead of an `optionalDependency`, so the solution added in https://github.com/js-platform/node-webrtc/commit/674606e62fad89cbdde49431dbca41e6462db107 probably isn't necessary anymore.

See:
https://github.com/feross/simple-peer/issues/14
https://github.com/feross/simple-peer/pull/16

**Comment by modeswitch** [comment]
@feross Thanks! I've merged @guymguym's PR.
