### ISSUE TITLE
Precompiled binaries for RPi

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#198]
@rosskukulinski Can you produce precompiled binaries for Raspberry Pi as well? Both ARMv6 and ARMv7 would be useful here.

**Comment by ghost** [comment]
Hi guys, any idea when this can be done?
Thanks for your time and work.

**Comment by modeswitch** [comment]
@kompsale Everyone here is volunteering their time, so there's really no way to guess.

If this is critical for you, please consider creating a bounty or donating to the project.

**Comment by ghost** [comment]
Hi,
$15 bounty
https://www.bountysource.com/issues/11906641-precompiled-binaries-for-rpi

**Comment by ghost** [comment]
Hi guys,
Is it really hard to make it run on Raspberry Pi? Can someone give a hint on how it can be done? Is it a lot of work?

**Comment by ralphtheninja** [comment]
I can help out with arm6

**Comment by ghost** [comment]
Hi Lars,
armv6 is specifically what I'm looking for.
Could you help with binaries or build script.

**Comment by ralphtheninja** [comment]
@kompsale I should be able to help out with binaries.

**Comment by ghost** [comment]
Hi Lars,
Just interested if you have any progress?

**Comment by ralphtheninja** [comment]
Sorry, no I've been busy with other things. I might take a look at it this weekend.

**Comment by bfishman** [comment]
Does anyone need armv71 binaries? I've managed to compile them to that arch. Was unsuccessful trying for v6.

Looking into how to automate this build, if successful I'll create a PR.

**Comment by haroldfredshort** [comment]
armv71 is all I was interested in, as that is what the Raspberry Pi 2 uses. Thanks for trying to figure it out.

**Comment by bfishman** [comment]
I'll do what I can to upload the armv71 files when I return home this weekend. Better late than never, I hope!

**Comment by bfishman** [comment]
Here you go. Armv71 binaries. Let me know if you have any issues getting it installed.

https://github.com/bfishman/node-webrtc-rpi-binaries

These were compiled with the latest stable version of node.

**Comment by markandrus** [comment]
Hi y'all, old thread here, but as of [v0.3.3](https://github.com/node-webrtc/node-webrtc/releases/tag/v0.3.3), we ship armv7l and arm64 binaries. They're only tested with QEMU in CircleCI, so it would be great if someone (who's still interested) could test these on a real device. armv6l is not shipping as of now, since

1. We still need a PR for armv6l support.
2. There are some issues with node-pre-gyp distinguishing armv6l from armv7l (the tool treats both as "arm", whereas arm64 is "arm").

**Comment by jmarunix** [comment]
Hello everyone, I have a raspberry pi zero w (armv6) and I'm trying, for fun ;-), compile the wrtc.node library for it.
The changes I made in the CMakeLists.txt file are the following(output of diff):
```
49a50,57
>     #arm_cpu="arm1176jzf-s"
>     arm_arch="armv6"
>     arm_version=6
>     arm_float_abi="hard"
>     arm_fpu="vfp"
>     #arm_thumb=false
>     arm_use_neon=false
>     arm_optionally_use_neon=false
60a69
> 
380c389,394
<   )
---
>     -march=armv6
>     #-mcpu=arm1176jzf-s
>     -mfloat-abi=hard
>     -mfpu=vfp
>     #-mno-thumb
> )
433c447,452
<     )
---
>       -march=armv6
>       #-mcpu=arm1176jzf-s
>       -mfloat-abi=hard
>       -mfpu=vfp
>       #-mno-thumb
>   )
439d457
< 
446,451c464,470
<         set(CMAKE_SYSROOT ${libwebrtc_source_dir}/src/build/linux/debian_sid_arm-sysroot)
<         target_compile_options(${MODULE} PRIVATE
<           -march=armv7-a
<           -mfloat-abi=hard
<           -mtune=generic-armv7-a
<           -mfpu=neon
---
> 	set(CMAKE_SYSROOT ${tools}/sysroot)
>        target_compile_options(${MODULE} PRIVATE
> 	  -march=armv6
> 	  #-mcpu=arm1176jzf-s
> 	  -mfloat-abi=hard
> 	  -mfpu=vfp
> 	  #-mno-thumb
453,454c472,473
<         set(CMAKE_C_COMPILER ${tools}/bin/arm-linux-gnueabihf-gcc)
<         set(CMAKE_CXX_COMPILER ${tools}/bin/arm-linux-gnueabihf-g++)
---
>         set(CMAKE_C_COMPILER ${tools}/prebuilt/bin/arm-linux-gnueabihf-clang)
>         set(CMAKE_CXX_COMPILER ${tools}/prebuilt/bin/arm-linux-gnueabihf-clang)
```
The only thing worth mentioning is to use Clang and the device's own sysroot, as well as to add the **arm_arch.h** file from openssl to the sysroot/usr/include/openssl directory.
After these changes the system compiles and links successfully, although the library is useless, as noted by @willmtemple in 
[https://github.com/node-webrtc/node-webrtc/issues/388](https://github.com/node-webrtc/node-webrtc/issues/388)
, but analyzing in depth each and every one of the libraries that make up wrtc.node, only 12 libraries are those that contain incompatible instructions (for NEONv1 and VFPv3).
Specifically, they are concentrated in the libwebrtc.a file and except one they all belong to Boringssl librarie, and they are:
```
Fichero:/mnt/DATOS/src/webrtc/node-webrtc/build/external/libwebrtc/build/Release/obj/third_party/boringssl/boringssl_asm/chacha-armv4.o
Fichero:/mnt/DATOS/src/webrtc/node-webrtc/build/external/libwebrtc/build/Release/obj/third_party/boringssl/boringssl_asm/aesv8-armx32.o
Fichero:/mnt/DATOS/src/webrtc/node-webrtc/build/external/libwebrtc/build/Release/obj/third_party/boringssl/boringssl_asm/armv4-mont.o
Fichero:/mnt/DATOS/src/webrtc/node-webrtc/build/external/libwebrtc/build/Release/obj/third_party/boringssl/boringssl_asm/bsaes-armv7.o
Fichero:/mnt/DATOS/src/webrtc/node-webrtc/build/external/libwebrtc/build/Release/obj/third_party/boringssl/boringssl_asm/ghash-armv4.o
Fichero:/mnt/DATOS/src/webrtc/node-webrtc/build/external/libwebrtc/build/Release/obj/third_party/boringssl/boringssl_asm/ghashv8-armx32.o
Fichero:/mnt/DATOS/src/webrtc/node-webrtc/build/external/libwebrtc/build/Release/obj/third_party/boringssl/boringssl_asm/sha1-armv4-large.o
Fichero:/mnt/DATOS/src/webrtc/node-webrtc/build/external/libwebrtc/build/Release/obj/third_party/boringssl/boringssl_asm/sha256-armv4.o
Fichero:/mnt/DATOS/src/webrtc/node-webrtc/build/external/libwebrtc/build/Release/obj/third_party/boringssl/boringssl_asm/sha512-armv4.o
Fichero:/mnt/DATOS/src/webrtc/node-webrtc/build/external/libwebrtc/build/Release/obj/third_party/boringssl/boringssl_asm/x25519-asm-arm.o
Fichero:/mnt/DATOS/src/webrtc/node-webrtc/build/external/libwebrtc/build/Release/obj/third_party/boringssl/boringssl_asm/poly1305_arm_asm.o
Fichero:/mnt/DATOS/src/webrtc/node-webrtc/build/external/libwebrtc/build/Release/obj/third_party/opus/opus/celt_pitch_xcorr_arm_gnu.o
```
Another detail is that of these, 8 **.S** files , of the sources, can be compiled(with Clang and against the mentioned sysroot) independently and generate object files for ARMv6.
Only the following 4 files are completely incompatible, even compiling the sources independently since it can be verified that they contain specific instructions for NEON and VFPv3:
```
Fichero:/mnt/DATOS/src/webrtc/node-webrtc/build/external/libwebrtc/build/Release/obj/third_party/boringssl/boringssl_asm/ghashv8-armx32.o
Fichero:/mnt/DATOS/src/webrtc/node-webrtc/build/external/libwebrtc/build/Release/obj/third_party/boringssl/boringssl_asm/x25519-asm-arm.o
Fichero:/mnt/DATOS/src/webrtc/node-webrtc/build/external/libwebrtc/build/Release/obj/third_party/boringssl/boringssl_asm/poly1305_arm_asm.o
Fichero:/mnt/DATOS/src/webrtc/node-webrtc/build/external/libwebrtc/build/Release/obj/third_party/opus/opus/celt_pitch_xcorr_arm_gnu.o
```
I'm not a C programmer or assembler in ARM, but my question is if it is possible to transcribe the instructions of these 4 files specifically for ARMv6 and if this would be useful to achieve an wrtc.node useful library.
