### ISSUE TITLE
Install prebuilt only without --fallback-to-build

### ISSUE THREAD

**Issue by feross** [node-webrtc/node-webrtc#200]
After using `wrtc` for a while now, I think there are some ways we can make it easier to use in real world projects (i.e. projects that we expect normal end users to install).

For packages that are used in both node and the browser (like `simple-peer`) some users will just want the browser functionality. I thought `optionalDependencies` was the solution, but it seems to be pretty unreliable for complicated build processes (https://github.com/feross/simple-peer/issues/14) and it only fails after a long download/build. I think we can do better.

One approach that works well is to release a separate `module-prebuilt` package. Electron and leveldown are doing this:

https://github.com/mafintosh/electron-prebuilt
https://github.com/mafintosh/leveldown-prebuilt

For `electron-prebuilt`, if there's no prebuilt binaries for your platform, the package just fails to install, without a fallback to build.

If I could depend on `wrtc-prebuilt` as an `optionalDependency` in `simple-peer` or `webtorrent`, then the users who just care about using it in the browser would be happy, and the node users can just open an issue and ask for a prebuilt for their platform. Some modules like `webtorrent` in node can still function just fine without WebRTC support. Without WebRTC, `webtorrent` is just a normal torrent client. :-)

**Comment by max-mapper** [comment]
huge +1. a way to try and grab a prebuilt binary that fails fast + gracefully without subjecting the user to walls of super unfriendly compile output and c++ build failure errors would help a lot

**Comment by modeswitch** [comment]
@feross What happens in the case where you do need to build from source?

**Comment by feross** [comment]
If there's no prebuilt binary available for your platform, the install should just fail. It's better for the installation to fail immediately than to try building from source. Building from source fails too often, takes too long, and confuses users.

There's obviously still a use case for falling back to source, so I'm suggesting this be a separate package on npm: `wrtc-prebuilt`.

Modules like `webtorrent` (torrent client over tcp, udp, webrtc) and `bittorrent-tracker` (tcp, udp, webrtc peer discovery), can still operate in a degraded fashion without `wrtc`, and I'd rather do that than make everyeone suffer through a slow install.

Also, browser+node modules like `simple-peer` would benefit from this too. If `wrtc-prebuilt` fails to install, then `simple-peer` could still be used in browserify.

**Comment by feross** [comment]
FYI, some context from the perspective of WebTorrent: https://github.com/feross/webtorrent/issues/303

**Comment by modeswitch** [comment]
@feross Happy to accept pull requests for this.

**Comment by markandrus** [comment]
Some breaking changes are coming up with v0.4.x and I think it's a good time to actually implement this. Rather than publish a `wrtc-prebuilt` package, I think we should instead

1. **Remove the option to build from source from NPM-published releases**<br>I agree with @feross that building from source is almost never what users want.<br>
2. **Maintain the ability to build from source when cloning from GitHub**<br>Still want to build from source? Add a dependency on `node-webrtc/node-webrtc#v0.4.0` in `package.json`.<br>

Implementing 1 and 2 will bring us closer to what, e.g., Electron is doing (they have a `package.json` marked `private` with a bunch of `devDependencies` and then a `package.json` for publishing to NPM).

**EDIT:** We can borrow from [this script](https://github.com/electron/electron/blob/master/script/publish-to-npm.js).

**Comment by feross** [comment]
This is excellent!
