### ISSUE TITLE
MediaStream Api

### ISSUE THREAD

**Issue by Jedius** [node-webrtc/node-webrtc#220]
Hi,
is there any way to implement media stream api, using any number of external libraries or whatever? did you have any progress with it, what is missing, where troubles?
I need to implement 1-to-many (very many, like 1 million) webcam translation with lowest possible delay, and will be cool if I can do it with nodejs instead of proprietary media servers like flash media server or slow c++ solutions like kurento, so I hope I can do something for make node-webrtc working with media streams.

**Comment by mafrost** [comment]
I am also interested in this subject.

**Comment by mitar** [comment]
+1

**Comment by jcimoch** [comment]
+1

**Comment by wanghaiquan** [comment]
+1

**Comment by lciruelo** [comment]
+1

**Comment by modeswitch** [comment]
Yes, media streams were supported in an earlier version of node-webrtc. I believe @markandrus is working on a new implementation, so they will be supported again in an upcoming version.

**Comment by markandrus** [comment]
Status update on my part: I proved this out in a personal branch a while ago with WebRTC 48 or so (other projects have proved it out as well). Before I get to it though I'd like to
- Get node-webrtc updated to a newer version of WebRTC (e.g., 51); we need to do this type of work anyway, since [libwebrtc](https://github.com/js-platform/libwebrtc) doesn't include MediaStream, etc.
- Separate out building WebRTC from building node-webrtc (e.g., by [precompiling binaries and packaging them separately](https://github.com/markandrus/build-webrtc)); this would replace/update libwebrtc and hopefully simplify many of the build issues reported in the issue tracker

Once we have these two pieces in place, I think it should be relatively easy to incrementally expose bindings to MediaStream, MediaStreamTrack, capturers, renderers, etc.

**Comment by rgranger** [comment]
+1 to know where we are with this feature 2 years later

**Comment by jb00ster** [comment]
+1 any news on this feature ?

**Comment by markandrus** [comment]
@rgranger @jb00ster

> +1 to know where we are with this feature 2 years later

I implemented the two bullet points I called out in my previous comment: we're now on M60 and builds are quick. node-webrtc can receive audio and video, but doesn't include the necessary APIs for surfacing remote MediaStreamTracks, adding local MediaStreamTracks, etc. So the next step is to start adding those necessary APIs. I have a PR [here](https://github.com/js-platform/node-webrtc/pull/393) that adds support for RTCRtpReceiver and remote MediaStreamTracks. @thedracle also has [a branch](https://github.com/js-platform/node-webrtc/issues/266#issuecomment-369347642) with some related work we should try to bring in. I am going to create a fresh issue with a checklist to capture future work.

**Edit:** here are some more detailed issues describing next steps to follow:

- #394 
- #395 
- #396

**Comment by markandrus** [comment]
#446 and v0.3.1 will introduce very limited `getUserMedia` support. MediaStreamTracks created this way will not transmit media (`bytesSent` and `bytesReceived` will be `0`). This PR also introduces RTCRtpTransceivers. Future work should focus on piping media in/out.

**Comment by markandrus** [comment]
My comment [here](https://github.com/node-webrtc/node-webrtc/issues/266#issuecomment-456279230) summarizes what is currently possible now, namely "relaying" MediaStreamTracks (not in the SFU sense) and sending/receiving raw I420 video frames. These APIs are fun, but I think the original request

> implement 1-to-many (very many, like 1 million) webcam translation with lowest possible delay

is far outside the scope of what is possible with node-webrtc. I know the original request is very old, but if anyone comes here looking for such a solution, please look for a proper [SFU](https://webrtcglossary.com/sfu/) instead. node-webrtc is not the proper solution.

---

I will close this issue now, as it's quite old, and there are other threads and releases that track the development of the MediaStream APIs.
