### ISSUE TITLE
Upload Binaries to S3

### ISSUE THREAD

**Issue by caseywebdev** [node-webrtc/node-webrtc#248]
Here is the wrtc@0.0.59 node-v47-linux-x64 build. I'm not sure why travis didn't publish these automatically. It's quite time-consuming to rebuild them every time.

[node-v47-linux-x64.tar.gz](https://github.com/js-platform/node-webrtc/files/70005/node-v47-linux-x64.tar.gz)

**Comment by bellini666** [comment]
Actually your build will not work on older `libstdc++` versions. I can run your build at my home using debian testing, but at my work, we use ubuntu trusty and trying to running it gives me this issue:

```
module.js:460
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/g/node-v47-linux-x64/wrtc.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

The issue happens because, since the compilation doesn't link statically to the `libstdc++`, it will try to use the one from the system, and in that case, the compilation used symbols that could not be found on the systems lib.

But if we compile the lib on an old `libstdc++`, it will still work on new ones. For example, I have the same problem compiling the binary on my debian testing and trying to run it on my ubuntu trusty machine. But if I compile it on the ubuntu trusty, it will run on both without any issues.

Also, another problem related to this issue is the lack of `ia32` binaries on s3. `npm install wrtc` will fail on 32bits machines since it will fallback to build, but that build [cannot be done on that arch](https://github.com/js-platform/libwebrtc/issues/15). IMO, to fix this issue, the latest release should always have builds for all platforms, all archs and all node abi versions (or at least the lts and the stable ones).

To finish, I had to compile some binaries to use on a project I'm developing, specially to avoid problems with 32bits machines. The solution I found was to run `node install wrtc --ignore-scripts` (as you [can see here](https://github.com/stoq/stoq-server/blob/master/data/webrtc/start.sh#L66)) and then download my binaries to the expected place. Those are the binaries that I generated for `wrtc@0.0.59`: [node-v46-linux-x64](https://s3.amazonaws.com/stoq-resources/wrtc_46_x64.node) and [node-v46-linux-ia32](https://s3.amazonaws.com/stoq-resources/wrtc_46_ia32.node)

cc: @nihey @romaia

**Comment by bellini666** [comment]
I saw that @markandrus made some changes recently and more binaries are being uploaded to s3 now. But there are one for ia32 there.

Is there any plans to make that happen? Lilke I said above, this issue is very annoying because there's no way to use this lib on 32bits machines: There's no binaries provided on s3 and the machine itself is not able to build it, so if you only have a 32bits machine you can't get this library to work.

**Comment by markandrus** [comment]
@hackedbellini if you can shares steps or a patch to get ia32 building with https://github.com/markandrus/build-webrtc and assuming I can get Travis CI to build for ia32 I would add it. Last I tried, I had some trouble getting WebRTC to build in such an environment. Things might be improved in newer WebRTC releases?

**Comment by bellini666** [comment]
@markandrus AFAIK, you just need to set `TARGET_BUILD=ia32` for that to work. At least it was what I did to when the build was still in this repository (by passing `--target=arch=ia32` to build.js https://github.com/js-platform/node-webrtc/commit/28902a47814084b44aaaf7014c80a4caa614b76a#diff-78d6e474ae315d0bea76cd46368acfedL32). I don't remember if I had to install something else (probably the 32bits version of the build dependencies and `ia32-libs`?)

**Comment by bellini666** [comment]
@caseywebdev is the issue resolved?

**Comment by caseywebdev** [comment]
I was just cleaning up some old issues and I've noticed this package doesn't take nearly as long to pull, so I assumed it was fixed. I'm not using any 32bit machines so maybe that's a separate, more specific issue?

**Comment by bellini666** [comment]
@caseywebdev the problem is another one. Basically, the way it is right now, there's no way to install this package in a 32bits machine. That happens because:

When you `npm install webrtc`, the (download-webrtc-libraries-and-headers)[https://github.com/js-platform/node-webrtc/blob/develop/scripts/download-webrtc-libraries-and-headers.js] will try to download an already compiled `wrtc` binary from s3. This is usually the case for 64bits, but there's none for 32bits.

If the download fails it will try to compile itself. It is fine for 64 bits again (as long as you have the dev packages installed), but the build will fail for 32 bits machine. That because there's no way to build wrtc for 32bits in a 32bits machine. To do that build, you need a 64bits machine while targeting `ia32`.

For that reason, it is impossible today to install this package in a 32bits machine by itself.

I described that problem a while ago in this issue (https://github.com/js-platform/libwebrtc/issues/15), but the solution would really be to start uploading the `ia32` binaries to s3 (which was being discussed here)
