### ISSUE TITLE
Video & Audio Support?

### ISSUE THREAD

**Issue by JerryFox1** [node-webrtc/node-webrtc#266]
Currently having issues just installing this thing on OSX 10.10
Can anyone who actually has gotten this working tell me if there is support for sending or receiving audio through the peerconnections node-webrtc offers?

This is really what I was interested using node-webrtc for. Rather not spend more time on this if it's not offered

**Comment by markandrus** [comment]
Hi @JerryFox1, I plan on adding audio/video support back to node-webrtc (I have prototyped it on my fork), but it currently does not support it. Regarding the install issue, I plan to look into this soon, as well. If you need audio/video support immediately, please take a look at some related projects. I will update this when audio/video support is added back.

**Comment by JerryFox1** [comment]
thank you for the reply! I'll take a look at your fork @markandrus, where can I find it btw?

**Comment by Joe-Palmer** [comment]
@markandrus I'd love to test video support on your fork but I cant find it. Can you provide a link to your fork or the related projects you mentioned? Many thanks.

**Comment by rijnhard** [comment]
hi @markandrus 

Just to recap (for everyone else) there was a fair bit of discussion/dev/investigating done on this over the years:
https://github.com/js-platform/node-webrtc/issues/25
https://github.com/js-platform/node-webrtc/pull/128
https://github.com/js-platform/node-webrtc/pull/138
https://github.com/js-platform/node-webrtc/issues/156
https://github.com/js-platform/node-webrtc/issues/220#issuecomment-222249316

So our use case is to use this to automate testing against SIP based systems, namely a product we have written in the [adhearsion](https://github.com/adhearsion/adhearsion) framework. The most critical part of the testing framework is what we dubbed **machine agents** which is basically a fake extension, that acts exactly like a WebRTC SIP extension and can answer calls. We want to feed our own media stream (either from TTS or a prerecorded file) as the **getUserMedia**.

The idea is to use mocha to define behavioral tests and make a framework for writing behavioral tests in SIP systems. I'd like to open source parts of it as well (as much as possible, we have some hefty proprietary API and redis usage that I'd need to strip out). 

We're using [SIP.js](https://github.com/onsip/SIP.js) for the SIP handling, I've dug through their code a fair bit, and managed to minimally wrap it to make node-webrtc's components the ones used for its WebRTC connection. But the MediaStream is proving a BIG PITA, at this rate I don't think I can get it working without it (unless there are any suggestions, since I'm doing this at work I have some time to allocate). 

I can also see MediaStream support in node-webrtc used to aid unit testing for things like SIP.js.

The alternative for us is to use raw asterisk (Probably via the shiny Rest API), but thats a whole other path, and makes it difficult to extend functionality in the code by comparison as we have to make changes in multiple places or do a lot more groundwork.

Also I'd propose closing the other remaining open issues and just using this for discussion

**Comment by rijnhard** [comment]
Just an FYI, I took @markandrus's [getUserMedia](https://github.com/markandrus/node-webrtc/tree/getUserMedia) branch and rebased it onto develop.
then merged in his [build-webrtc-separately](https://github.com/markandrus/node-webrtc/tree/build-webrtc-separately) branch. 

I had to update and refactor some code, but no major changes (yay for my rusty C++) 
it now compiles. (I also made a dockerfile for compilation) 

I'm just trying to sort out some more userland problems, like feeding my own audio stream as the source for `getUserMedia` and what to do with the stream I get back. then I can see if it actually works.

**Comment by alexanderb14** [comment]
Any progress on this from your end?

Over the last days I have
- updated WebRTC to the most recent version
- implemented MediaStream, MediaStreamTrack and GetUserMedia APIs

I verified that it works for both Audio and Video. However, I didn't use the monolithic libwebrtc as it produced an error with the videocapturerdevice != null.

**Comment by rijnhard** [comment]
@alexanderb14 I took my progress and made a PR. We ended up using Asterisk 13's ARI directly. Which proved better overall for our use case.

**Comment by alexanderb14** [comment]
@rijnhard could you give me a link to the PR, please? Just to see how much of an overlap we have and what I can contribute. 

The issue in webrtcbuilds has been fixed by the way:
https://github.com/vsimon/webrtcbuilds/issues/7

**Comment by rijnhard** [comment]
@alexanderb14 https://github.com/markandrus/node-webrtc/pull/1

**Comment by Rush** [comment]
Will Video & Audio support break data-only use cases? I am currently using node-webrtc on servers which have no audio/video. 

I guess the question is, is audio & video completely optional? is there a possibility for a slimmer build that's data only? I guess that webtorrent guys would also prefer slimmer data only option.

**Comment by alexanderb14** [comment]
yes and no for my fork that I have currently locally:
- it doesn't break data-only use cases
- but it makes the node-webrtc heavier

The build of WebRTC (monolithic static library from webrtcbuilds github project) which is currently used in the master branch appears to be slimmed out for media. Can someone comment on how this has been slimmed out?

**Comment by Robbilie** [comment]
seems like this issue aswell as comments on https://github.com/markandrus/node-webrtc/pull/1 died on sep 22/23. ^^

i guess you two havent had any more time to work on this, @rijnhard & @markandrus ? :)

**Comment by rijnhard** [comment]
@Robbilie I stopped working on it as it's a bit far outside of my expertise and we went another route, I dont know about @markandrus

**Comment by stanleynguyen** [comment]
Any updates on this as of today? I still see in the docs that Media Stream API is not supported but can anyone please clarify? @rijnhard @alexanderb14 @markandrus

**Comment by alexanderb14** [comment]
I don't know about the plans of the official node-webrtc project. But as far as I understand, it is not wanted to integrate because the WebRTC stack with audio/video is more heavy weight than the data channel only. Maybe @markandrus can comment?

BTW: My branch at alexanderb14/node-webrtc-mediastream worked in late 2016. It has been successfully used in a private project.

**Comment by rijnhard** [comment]
@stanleynguyen sorry can't provide any meaningful feedback, I went another route and used Asterisk to handle the media via its rest interface. I do still think that this should be something, even if a separate lib.

**Comment by stanleynguyen** [comment]
Thank you so much @rijnhard and @alexanderb14 
Could you provide me with an example how to use your branch @alexanderb14 for MediaStream API? There doesn't seem to be any documentation

**Comment by ivatsa** [comment]
@alexanderb14, I am trying to follow the instruction on your [project page](https://github.com/alexanderb14/node-webrtc-mediastream)
During **npm install** I hit a 404 response (broken link?) when trying to get binaries:

    node-pre-gyp ERR! Tried to download(404): https://node-webrtc-full.s3.amazonaws.com/wrtc/v0.0.67/Release/node-v57-darwin-x64.tar.gz 

Later it tries to compile source and hits a 403 response on:

    https://s3.eu-central-1.amazonaws.com/webrtc-prebuilts/v1/build/webrtcbuilds-14726-764e364-mac-x64.zip

Any help or advice around this would be great. Thanks

PS: I don't mean to pollute this thread but could not find issues section on the project page

**Comment by thedracle** [comment]
I'm trying to resurrect @alexanderb14's work against the latest node-webrtc branch.

I basically manually applied his patches where it makes sense (Rather than cherry-picking/merging, since some parts do not seem to make sense anymore).

Mainly the webrtc library that is being linked to already in node-webrtc supports everything we need to wire up mediastreams.

I've also wired up the 'mediastream' event, so we can retrieve RTCMediaStream objects when they are added to the PeerConnection (alexanderb14's branch didn't seem to support this yet).

I'm going to try now to add the ability to transparently add sinks, and tap into data from the remote video and audio tracks.

Building should be the same as the current node-webrtc master branch:

Make sure gcc & g++ 4.8 are already installed:
```
export CC=gcc-4.8
export CXX=g++-4.8
npm install --build-from-source
```

At the moment I'm just softlinking it to the node_modules directory in the project that I am testing with.

This is totally a work in progress, but any help or suggestions would be greatly appreciated:
https://github.com/thedracle/node-webrtc/tree/mediastream

**Comment by ivatsa** [comment]
@thedracle Thats awesome! I will keep a close eye on your project.

I am particularly interested for a node module to handle incoming/remote MediaStream and forward it ahead to say a a browser based client.

Do you have any suggestions on reading material around RTCMediaStream so that I can be helpful in terms of code contribution?

**Comment by thedracle** [comment]
@ivatsa,

Yeah, I'm very interested in this behavior as well. 

I've used raw C++ and Google's WebRTC implementation at the moment to record, or bridge to WebRTC from other protocols. Usually this involves reimplementing SIP/XMPP, or some other signaling in C++.

I have been using headless Electron/NWJS, but they're very heavy weight, so I'm hoping I can leverage node-webrtc to deal with this.

The C++ API for webrtc::MediaStreamInterface is very similar to the JS API. It has methods to get lists of tracks, and inside that methods to add sinks to those tracks (Which get passed raw PCM/YUV data).

As far as just taking a foreign MediaStreamInterface from one PeerConnection, and using AddStream on another to add it (With WebRTC handling forwarding the stream internally)--- I think this ought to just work.

At the moment on my branch the RTCMediaStream objects being created are just stub objects, I will start adding properties to mock it up like the standard as soon as I finish with wiring up the ability to read the raw video/audio from streams (I need it for my current use case).

**Comment by markandrus** [comment]
@thedracle maybe check out the node_webrtc::PeerConnectionFactory (PCF) that landed in 0.0.66. It wraps a webrtc::PeerConnectionFactoryInterface (PCFI). The PCFI has methods

* `CreateLocalMediaStream`,
* `CreateAudioTrack`, and
* `CreateVideoTrack`.

these could be surfaced on the PCF (e.g., as the standard MediaStream constructor, and maybe some non-standard constructors or functions for creating MediaStreamTracks). The resulting NAN objects should probably track the PCF they were created with, and node_webrtc::PeerConnection should probably throw if `addTrack`/`addStream` are invoked with MediaStreams or MediaStreamTracks from the "wrong" PCF.

**Comment by thedracle** [comment]
@markandrus, Thanks for the pointers, I'll start looking at Creating local Audio/Video tracks after I finish with the work for receiving remote tracks.

I've added onto my branch so far the ability to register a callback to receive decoded video frames, and to trigger a stream to start sending these frames.

Now I am working on hooking to raw encoded VP8 data directly from the remote streams.

@markandrus, I was wondering if there was already an easy way to do a debug build. I've tried ncmake with -d, and it doesn't appear to generate a .node module with debug symbols.

**Comment by markandrus** [comment]
@thedracle sweet 👍 feel free to open a PR, or i'll take a look at your branch when i have some time.

> I've added onto my branch so far the ability to register a callback to receive decoded video frames, and to trigger a stream to start sending these frames.

This is cool. I think it will be important to identify some use cases we want to satisfy. E.g.,

1. **Simple "echo" server that allows retransmitting received MediaStreamTracks** — useful for testing WebRTC applications, should be performant, can probably reuse the dummy AudioDeviceModule and forego any capturer
2. **Applications that allow sending frames from a "real" webcam or samples from a "real" microphone** — would use the platform default AudioDeviceModule, would probably need to opt-in (so as to avoid the symbol errors in, e.g., DataChannel-only deployments where PulseAudio and/or ALSA are unavailable)
3. **Applications that allow programmatically handling received frames** — also useful for testing WebRTC applications, but maybe not as performant if we're transmitting, e.g., ArrayBuffers between Node and C++
4. **Applications that allow programmatically sending frames** — also useful for testing, but same caveat as above
5. **Others...?** — have to think about it.

None of these are mutually exclusive, but I think we should try to figure out how to support all without sacrificing performance in 1, 2, and the DataChannels-only use case. WDYT?

> @markandrus, I was wondering if there was already an easy way to do a debug build. I've tried ncmake with -d, and it doesn't appear to generate a .node module with debug symbols.

Hmm, maybe check CMakeLists.txt? Perhaps we need to explicitly add `-g`? Also, I think if you previously built a Release build, you may need to `rm -rf build && ./node_modules/.bin/ncmake rebuild --debug`.

**Comment by thedracle** [comment]
@markandrus,

>None of these are mutually exclusive, but I think we should try to figure out how to support all without sacrificing performance in 1, 2, and the DataChannels-only use case. WDYT?

Yeah, DataChannels are intrinsically important to my current use-case, and definitely we need to make sure they still function normally.

I can see passing an ArrayBuffer for each frame being not particularly efficient--- another possibility would be to have JS pass a buffer down, and for the module to just fill the memory behind it with YUV/RGB frames, and signal the NodeJS app on every frame. It would be up to Node to queue and preserve a frame for long-term processing before it gets overwritten again.

> 1. Simple "echo" server that allows retransmitting received MediaStreamTracks 

So I know if you're using Chromium, and the standard PeerConnection API, it has been possible for some time to publish a remote MediaStream to another PeerConnection.

I'm going to explore if this is something intrinsic to the PeerConnection library underneath, or some magic they are performing in Chromium. 

In the meantime I have figured out how to register a decoderFactory, and to make a proxy interface to capture VP8 encode requests, and to hook it into a callback, so now we can get both raw VP8 for each frame, as well as the decoded YUV frame.

I'll start working on Audio input next. I don't think based on the API it will be possible to get raw OPUS from the PeerConnection, so we will just grab the remote PCM samples and deliver them to JS.

**Comment by thedracle** [comment]
Merged/squashed against latest in develop:
https://github.com/thedracle/node-webrtc/tree/mediastream-rebase-squash

Started working on rudimentary support for getVideoTracks, that can be iterated over to subscribe to the onvideoframe, and onencodedvideo frame callbacks.

**Comment by McPo** [comment]
My company would have an interest in sponsoring this feature, to give it the final push over the line.

The request would be Audio and Video. (Although video is not an immediate ask).
It must be possible to pipe audio from a file over the stream. (Our use case is for load testing our infrastructure) 
Finally it would need to be robust and accepted as a PR into master.

@alexanderb14 I tried your solution back in December and got it working, however there appeared to be an issue with destroying the connection and starting a new one. Subsequent calls seems to have caused a native crash.  Although I spent limited time looking into it. @thedracle I am yet to try your solution, so Im not sure how far along it is.

Anyway If your interested could you contact damian.horner@saltdna.com.

**Comment by McPo** [comment]
Ive added the ability to load from an audio file and pipe it over a MediaStream, as a PR to thedracle fork. Incase its of interest to anyone.

**Comment by markandrus** [comment]
Checking in on the list I shared [previously](https://github.com/node-webrtc/node-webrtc/issues/266#issuecomment-365467266):

>  1. **Simple "echo" server that allows retransmitting received MediaStreamTracks** — useful for testing WebRTC applications, should be performant, can probably reuse the dummy AudioDeviceModule and forego any capturer
> 2. **Applications that allow sending frames from a "real" webcam or samples from a "real" microphone** — would use the platform default AudioDeviceModule, would probably need to opt-in (so as to avoid the symbol errors in, e.g., DataChannel-only deployments where PulseAudio and/or ALSA are unavailable)
> 3. **Applications that allow programmatically handling received frames** — also useful for testing WebRTC applications, but maybe not as performant if we're transmitting, e.g., ArrayBuffers between Node and C++
> 4. **Applications that allow programmatically sending frames** — also useful for testing, but same caveat as above

Item 1 has been satisfied since [v0.1.5](https://github.com/node-webrtc/node-webrtc/releases/tag/v0.1.5), released in June. Items 3 and 4 are satisfied as of [v0.3.5](https://github.com/node-webrtc/node-webrtc/releases/tag/v0.3.5), released today. v0.3.5 allows sending and receiving raw I420 video frames via two non-standard APIs, RTCVideoSource and RTCVideoSink. Items 3 and 4 should be extended to support audio as well (tracked in #478). Item 2 is not started on.

@thedracle 

> I can see passing an ArrayBuffer for each frame being not particularly efficient--- another possibility would be to have JS pass a buffer down, and for the module to just fill the memory behind it with YUV/RGB frames, and signal the NodeJS app on every frame. It would be up to Node to queue and preserve a frame for long-term processing before it gets overwritten again.

I did not implement this in v0.3.5, but I think it's still a good idea and an optimization worth making in a subsequent release.

**Comment by markandrus** [comment]
I'm beginning work [binding RTCAudioSource and RTCAudioSink](https://github.com/node-webrtc/node-webrtc/pull/479) for Programmatic Audio support. This should support items 3 and 4, but for audio, on the list. Once completed, I think we should close this issue, since basic building blocks for support audio and video will be completed. IMO, accessing the local microphone/webcam from Node (Item 2 on the list) is a separate feature we can tackle afterwards with a dedicated issue.

**Comment by markandrus** [comment]
As of [v0.3.6](https://github.com/node-webrtc/node-webrtc/releases/tag/v0.3.6), you can get send and receive audio samples represented as Int16Arrays using the RTCAudioSource and RTCAudioSink APIs.

**Comment by paco3346** [comment]
Just want to leave this here for anyone else interested in doing local mic capture in node.
@markandrus I owe you a beer/coffee/kombucha.

```javascript
const wrtc = require('wrtc');
const mic = require('mic');

const sampleRate = 48000;
const sliceSize = sampleRate / 100; //gives us 10 ms chunks
const channels = 1;
const bitrate = 16;

var micInstance = mic({
  endian: 'little',
  encoding: 'signed-integer',
  rate: sampleRate,
  channels: channels,
  bitwidth: bitrate,
  device: 'whatever your device is'
});

const { RTCAudioSource } = require('wrtc').nonstandard;

const source = new RTCAudioSource();
const track = source.createTrack();

let samples = new Int16Array(0);
let micInputStream = micInstance.getAudioStream();

//every time we get data from the mic append it to the existing buffer
micInputStream.on('data', function(data) {
  let newSamples = new Int16Array(data.buffer);
  let mergedSamples = new Int16Array(samples.length + newSamples.length);
  mergedSamples.set(samples);
  mergedSamples.set(newSamples, samples.length);
  samples = mergedSamples;
});


setInterval(() => {
//if there's enough data to read slice off 10ms worth and pass it to the track
  if (samples.length >= sliceSize) {
    let sampleSlice = samples.slice(0, sliceSize);
    samples = samples.slice(sliceSize);
    source.onData({
      samples: sampleSlice,
      sampleRate: sampleRate,
      bitsPerSample: bitrate,
      channelCount: channels,
      numberOfFrames: sampleSlice.length
    });
  } else {
    console.log('buffer underrun detected');
  }
}, 10); //10 ms chunks

micInstance.start();

//not shown: code that actually adds the track to a stream, etc
```
