### ISSUE TITLE
Pre-compiled Binary hosting warning

### ISSUE THREAD

**Issue by rosskukulinski** [node-webrtc/node-webrtc#274]
Hello,

My startup has been hosting the pre-compiled node-webrtc binaries in our S3 account for the last year or two.  We're winding down our company and later this year will be shutting down our AWS account.  As such, the node-webrtc team should look to find another sponsor for hosting the binaries.  I'm happy to help with the transition of existing binaries in the S3 account to a new account.

Thanks,
Ross

**Comment by markandrus** [comment]
Hi @rosskukulinski, thanks for the heads up. Can you please share
1. The S3 bucket in question (I am not sure if it is the one currently configured)
2. Which versions of node-webrtc are affected, and
3. Which platforms and architectures the binaries were built for?

**Comment by rosskukulinski** [comment]
1. [node-webrtc](https://node-webrtc.s3.amazonaws.com)
2. From looking at the bucket:
   - v0.0.49
   - v0.0.50
   - v0.0.51
   - v0.0.52
   - v0.0.53
   - v0.0.54
   - v0.0.55
   - v0.0.58 (Last darwin release)
   - v0.0.60
3. From looking at the bucket, it differs over the versions but in short:
   - node-v11-linux-x64
   - node-v11-darwin-x64
   - node-v14-linux-x64
   - node-v47-linux-x64
   - node-v48-linux-x64

**Comment by markandrus** [comment]
@rosskukulinski thank you very much for this information.
1. Is it possible to transfer S3 buckets between Amazon accounts? I have an Amazon account, and I would be willing to host (I assume it is not too expensive...).
2. If not, we will not be able to update the URLs for the releases you identified, since NPM releases are immutable. In that case, I expect new installs of these releases will fallback to building from source. I think this is acceptable.

I have an S3 bucket I was planning to use for pre-built WebRTC binaries, [webrtc-libraries-and-headers](https://webrtc-libraries-and-headers.s3.amazonaws.com), that I would be willing to re-use if we cannot transfer the bucket. I could also create a new bucket.

Going forward, it may also be worth considering some free alternatives to S3. For example,
- [node-pre-gyp-github](https://www.npmjs.com/package/node-pre-gyp-github)
- Bintray ([elmlang uses them](https://github.com/elm-lang/elm-platform/issues/94))

**Comment by rosskukulinski** [comment]
hi @markandrus -
1. We can't transfer, but we can use `aws s3 sync` to transfer: https://aws.amazon.com/premiumsupport/knowledge-center/account-transfer-s3/  As for price - we haven't paid a cent for the s3 storage for node-webrtc :)
2. Yes, I think old builds we start falling back to from source.  This is an unfortunate aspect of the fact that we're not following SemVer.  If we were, we could issue patch releases for each version to switch s3 bucket.

I _believe_ the current s3 bucket has necessary permissions for you to sync from it, but please let me know if that's not the case.  It sounds like I would need the 12-digit account Id for the destination account to udpate the bucket policy on my end.  You can contact me at ross@getyodlr.com with that account id if the sync doesn't work.

**Comment by markandrus** [comment]
@rosskukulinski thanks again for all the info. I'll attempt the `aws s3 sync` and followup. Also, AFAICT, once you release the bucket name I might be able to reclaim it so long as no-one beats me to it.

**Comment by markandrus** [comment]
I was able to synch the existing wrtc binaries from the node-webrtc bucket. Once @rosskukulinski released the bucket, I reclaimed it, synched the wrtc binaries back to the "new" node-webrtc bucket, and—after fiddling with the permissions a bit—got pre-compiled installs working again. Test with the latest build, 0.0.60, on Linux. Thanks again, @rosskukulinski!

**Comment by rosskukulinski** [comment]
Awesome - thanks for taking this over @markandrus
