### ISSUE TITLE
Where do the binaries come from?

### ISSUE THREAD

**Issue by JustinDrake** [node-webrtc/node-webrtc#310]
Maybe add a link in the README.md explaining where the binaries come from.

**Comment by roccomuso** [comment]
I agree

**Comment by markandrus** [comment]
Open to suggestions on how to present the information here. The binaries live in the node-webrtc S3 bucket. For example, here are the paths to the Node 8 binaries:

* https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.62/Release/node-v57-darwin-x64.tar.gz
* https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.62/Release/node-v57-linux-x64.tar.gz
* https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.62/Release/node-v57-win32-x64.tar.gz

We use [`node-pre-gyp`](https://github.com/mapbox/node-pre-gyp) to publish these when we tag a release or include the string `[publish binary]` in a commit message. Here's example job output:

```
$ if [[ $TRAVIS_TAG ]] || [[ `git show -s --format=%B $TRAVIS_COMMIT` == *'[publish binary]'* ]]; then $RUN node_modules/.bin/node-pre-gyp package publish; fi
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.36
node-pre-gyp info using node@8.1.4 | darwin | x64
node-pre-gyp info package packing /Users/travis/build/js-platform/node-webrtc/build/wrtc/v0.0.62/Release/node-v57-darwin-x64
node-pre-gyp info package packing /Users/travis/build/js-platform/node-webrtc/build/wrtc/v0.0.62/Release/node-v57-darwin-x64/wrtc.node
node-pre-gyp info package Binary staged at "build/stage/wrtc/v0.0.62/Release/node-v57-darwin-x64.tar.gz"
node-pre-gyp info publish Detecting s3 credentials
node-pre-gyp info publish Authenticating with s3
node-pre-gyp info publish Checking for existing binary at https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.62/Release/node-v57-darwin-x64.tar.gz
node-pre-gyp info publish Preparing to put object
node-pre-gyp info publish Putting object
node-pre-gyp info publish returned from putting object
node-pre-gyp info publish s3 putObject response: "{"ETag":"\"b0895059fba2ca26bfc1a733fa76d272\""}"
node-pre-gyp info publish successfully put object
[wrtc] published to https://node-webrtc.s3.amazonaws.com/wrtc/v0.0.62/Release/node-v57-darwin-x64.tar.gz
node-pre-gyp info ok 
```

On `npm install`, `node-pre-gyp` will fetch the binary, if it exists. Otherwise it will fallback to building from source.

Additionally, `node-pre-gyp` needs to get the information about where to publish/download the binaries. This information lives in the `binary` section of `package.json`. Here's an excerpt:

```json
{
  "binary": {
    "module_name": "wrtc",
    "module_path": "./build/{module_name}/v{version}/{configuration}/{node_abi}-{platform}-{arch}/",
    "remote_path": "./{module_name}/v{version}/{configuration}/",
    "package_name": "{node_abi}-{platform}-{arch}.tar.gz",
    "host": "https://node-webrtc.s3.amazonaws.com"
  }
}
```

**Comment by markandrus** [comment]
Added to the wiki [here](https://github.com/node-webrtc/node-webrtc/wiki/Where-do-the-binaries-come-from%3F).
