### ISSUE TITLE
Regression in v0.1.0 : setRemoteDescription don't work

### ISSUE THREAD

**Issue by alaa-eddine** [node-webrtc/node-webrtc#381]
Hi,

I just updated to the latest version, a it seems that setRemoteDescription is not working now.
I'm trying to estabilish a connection with a datachannel, when I call setRemoteDescription I never get a success nor failure callback .

same code works just fine with v0.0.67

**Comment by markandrus** [comment]
Hi, can you please share a code sample? We have tests around this, so I’m very curious as to what may have changed.

**Comment by alaa-eddine** [comment]
Sure, but I'm afraid that my present code isn't simple.
it's used in my RPC library (https://github.com/Ezelia/eureca.io) where I use wrtc as a transport layer among others.

the code that use wrtc can be found here : https://github.com/Ezelia/eureca.io/blob/master/src/transport/WebRTCPeer.ts it's in typescript.
The setRemoteDescription that don't work can be found at the very end of this code (line 300).

The logic behind is as follow.
 * A client uses create a peer connection and make an offer, then post the offer data to the server.
 * The server receives the posted data and create a peer connection, initiate some events listeners, and call getOffer method which is supposed to accept the offer throught setRemoteDescription ... but here the code get stuck and the callbacks (success/failure) are never triggered.

I hope that this can help.

**Comment by markandrus** [comment]
Thanks a lot, @alaa-eddine — this will help. Here is one thing I see: on [lines 62 and 63](https://github.com/Ezelia/eureca.io/blob/master/src/transport/WebRTCPeer.ts#L62), you are using the legacy version of RTCIceServer. The legacy `url` property was replaced with `urls` in the WebRTC spec. For a long time, node-webrtc accepted both formats. Now it only supports the standard. I tried to call this out in the [CHANGELOG.md under "Breaking Changes"](https://github.com/js-platform/node-webrtc/blob/v0.1.0/CHANGELOG.md#breaking-changes), but it's easy to miss. Can you try changing those lines to

```ts
public cfg = {
  iceServers: [
    { urls: 'stun:stun.l.google.com:19302' },
    { urls: 'stun:stun1.l.google.com:19302' }
  ]
};
```

Maybe that will help get further? It's strange, though, that the callbacks don't trigger, since I think those should fire independently of valid/invalid `iceServers`.

**Comment by alaa-eddine** [comment]
wow that was the cause of my issue ! thank you very much @markandrus 

what drove me crazy is that yesterday everything was working just fine, but today after the release I wanted to make a final check just in case .... and it was broken :D .... my bad, I noticed that wrtc version changed but didn't though to read the changelog.
I was so excited to release a new version of my library with webrtc support that I forgot the basics :D 

I'm following this project for a while and was waiting for it to be able to provide webrtc based transport, I'm very happy to see it alive and quite advanced stable.

thank you again, and keep up the excellent job 👍

**Comment by markandrus** [comment]
Thanks for your support, and I’m glad that fixed it! :-)
