### ISSUE TITLE
Breaking changes or bug: createDataChannel returns undefined value

### ISSUE THREAD

**Issue by webarchymeta** [node-webrtc/node-webrtc#382]
version: 0.1.0:
platform: Windows 10, Ubuntu 16.04

Breaking changes or bug:

```
createDataChannel([some string label])
```
of a `RTCPeerConnection` instance returns `undefined` 'value'. This is happening to a previously (wrtc 0.0.67) working lib of ours that I am using

**Comment by markandrus** [comment]
Hi @webarchymeta, thanks for the report. This issue is also captured in https://github.com/js-platform/node-webrtc/issues/314. I will open a PR to fix this shortly. Note that, we only return `undefined` if the RTCPeerConnection is already closed. According to [the spec](https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-createdatachannel), we should instead throw an InvalidStateError:

> If connection's [[IsClosed]] slot is true, throw an InvalidStateError.

**Comment by markandrus** [comment]
Released in 0.1.1
