### ISSUE TITLE
Please update the build instructions

### ISSUE THREAD

**Issue by Nuru** [node-webrtc/node-webrtc#434]
I would investigate #391 and #435 further but I'm too confused about how to build a debug version of `node-webrtc`. The build instructions in the [README](https://github.com/js-platform/node-webrtc) say they need to be updated for WebRTC M60 and refer to https://github.com/aisouard/libwebrtc. The [Wiki](https://github.com/js-platform/node-webrtc/wiki/Building) says to use [`build-webrtc`](https://github.com/markandrus/build-webrtc). I could probably figure something out, but I want to make sure I'm building the debugging version of release v0.2.0 and not some other hybrid that will only create more confusion.

Would you please update the build instructions and explain how to build and install `node-webrtc` with debugging symbols?

**Comment by janderland** [comment]
Because `node-webrtc` is now using M60, we should be able to drop the `DWEBRTC_BRANCH_HEAD` argument from the Cmake command because `libwebrtc` defaults to building M60. That section of the Readme should now look like this:
```
git clone https://github.com/aisouard/libwebrtc
cd libwebrtc
mkdir out
cd out
# include the bracketed part for generating a debug build
cmake [-DCMAKE_BUILD_TYPE=Debug] ..
make
# wait for a while
cd <path of node-webrtc>
mkdir -p third_party/webrtc
cp -r <path of libwebrtc>/out/lib third_party/webrtc
cp -r <path of libwebrtc>/out/include third_party/webrtc
export SKIP_DOWNLOAD=true
export CC=gcc-4.8
export CXX=g++-4.8
npm run install
```

The only reason I haven't thrown up a pull request for this yet is because `libwebrtc` seem to be failing to build on the latest version of MacOS (10.13.6) and Xcode (10.0). The generated makefile cannot find the following folder: `/Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs`. I'm guessing this is because Xcode moved the SDK files to elsewhere. In that case, the `libwebrtc` Cmake files will need updating.

Should I put up a pull request for the readme update anyways? Can anyone else test the build on Windows or Linux?

**Comment by markandrus** [comment]
Hi @Nuru,

I think #445 addresses this. v0.3.0 will not depend on aisouard/libwebrtc anymore. Instead, we'll handle building WebRTC ourselves in CMakeLists.txt. This also means, if you do

```
ncmake rebuild --debug
```

you should get debugging symbols for both node-webrtc and WebRTC (along with a bunch of extra logging, WebRTC's thread checker, etc.). As for the Wiki, I will remove the outdated information.
