### ISSUE TITLE
Standalone example for DataChannels.

### ISSUE THREAD

**Issue by DrMiaow** [node-webrtc/node-webrtc#495]
Are there any examples that can be run with just the installed 'wrtc' node module?

Looks like the only way to get `/examples` operational is to build from source, or am I missing something?

Thanks.

**Comment by markandrus** [comment]
Hey @DrMiaow, if you `git checkout v0.3.6` and `npm install` that, it ought to install the prebuilt wrtc.node binary rather than build from source. That should easily get you going for now.

However, I suppose we might want to separate the example app out into its own project that depends on wrtc directly.

**Comment by markandrus** [comment]
@DrMiaow I extracted the example app out into this repo: https://github.com/node-webrtc/node-webrtc-examples
