### ISSUE TITLE
Updated examples using `dist/wrtc.js` are broken

### ISSUE THREAD

**Issue by modeswitch** [node-webrtc/node-webrtc#51]
```
Uncaught ReferenceError: mozRTCIceCandidate is not defined wrtc.js:2
Uncaught ReferenceError: require is not defined test.js:1
```

**Comment by modeswitch** [comment]
@piranna Can you add some code to build.js to generate dist/wrtc.js using browserify?

**Comment by piranna** [comment]
Yes, I can, it's easy. I didn't do it and just uploaded a generated file
since it's almost impossible it will change ever :-P

2014/1/23 Alan K notifications@github.com

> @piranna https://github.com/piranna Can you add some code to build.js
> to generate dist/wrtc.js using browserify?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/js-platform/node-webrtc/issues/51#issuecomment-33127683
> .

## 

"Si quieres viajar alrededor del mundo y ser invitado a hablar en un monton
de sitios diferentes, simplemente escribe un sistema operativo Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by modeswitch** [comment]
I believe this is fixed now.
