### ISSUE TITLE
Application-specific Track Names

### ISSUE THREAD

**Issue by csheely** [node-webrtc/node-webrtc#546]
Our application requires the ability to provide custom names to WebRTC tracks that are readable/accessible to the other side of the session/call.

The underlying WebRTC `PeerConnectionInterface::AddTrack()` method allows the caller to pass in a vector of strings representing stream labels to associate the track with.  This allows the remote side to retrieve the stream the track belongs to and to read the steam name.  However, the current node-webrtc `RTCPeerConnection::AddTrack()` method expects an optional `MediaStream` object pointer, from which a string identifier is extracted.  Node-webrtc users have no access to `MediaStream` objects themselves, so this optional parameter appears to serve no purpose today. _(Edit: I now see that we can create MediaStream objects from node-webrtc and use them, but the `id` field is auto-generated and read-only.)_

We have modified `RTCPeerConnection::AddTrack()` in rtc_peer_connection.cc to allow passing in a string instead of a MediaStream object pointer, to more closely mirror the underlying API (see "// NEW:" comments in snippet below).  Ideally this would be a vector of strings to model the native API's, but we would like feedback on this approach, before submitting a GIT pull request.

```c++
Napi::Value RTCPeerConnection::AddTrack(const Napi::CallbackInfo& info) {
  auto env = info.Env();
  if (!_jinglePeerConnection) {
    Napi::Error(env, ErrorFactory::CreateInvalidStateError(env, "Cannot addTrack; RTCPeerConnection is closed")).ThrowAsJavaScriptException();
    return env.Undefined();
  }
  // NEW: third arg includes a maybe string instead of MediaStream
  CONVERT_ARGS_OR_THROW_AND_RETURN_NAPI(info, pair, std::tuple<MediaStreamTrack* COMMA Maybe<std::string>>)
  auto mediaStreamTrack = std::get<0>(pair);
  // NEW: extract the string instead of MediaStream
  Maybe<std::string> mediaStreamID = std::get<1>(pair);
  std::vector<std::string> streams;

  if (mediaStreamID.IsJust()) {
    // NEW: add the new string / ID directly to the streams vector
    streams.push_back(mediaStreamID.UnsafeFromJust());
  }
  auto result = _jinglePeerConnection->AddTrack(mediaStreamTrack->track(), streams);
  if (!result.ok()) {
    CONVERT_OR_THROW_AND_RETURN_NAPI(env, &result.error(), error, Napi::Value)
    Napi::Error(env, error).ThrowAsJavaScriptException();
    return env.Undefined();
  }
  auto rtpSender = result.value();
  return RTCRtpSender::wrap()->GetOrCreate(_factory, rtpSender)->Value();
}
```

Please let us know what you think of this approach.  Thank you.

**Comment by markandrus** [comment]
Hi @csheely,

Thanks for writing and your PR. I would prefer not to land this version of the change. Instead, what about

1. Working around this in application code? I.e., have a map between the auto-generated MediaStream ID and the application-specific ID
2. Instead, extend the MediaStream constructor to accept an object with a user-suggested ID? (Don't know the implications of ID collisions, though&hellip;)

**Comment by sgodin** [comment]
Hi Mark,

Thank-you for your feedback!

I'm working with Chris on this issue.  

While option #1 is likely doable, it really complicates our logic, since this would mean additional application level messages passed between the server and the client to map the gen'd id's to the client provided names.  We prefer to avoid this option.

Option #2 would work for us, but we want to make sure this is really the right direction.  From what I can gather, at one point in time the C++ (webrtc.org) version of PeerConnectionInterface::AddTrack used to take a MediaStream pointer, to allow you associate the track to a particular media stream.  So you offered this same interface on the javascript side.  Then the webrtc.org code base changed from using a MediaStream pointer to a vector of media stream names.  I'm assuming this was done by google along with many other changes for Unified Plan support.   After webrtc.org made that change you modified your code in-step in your project, however, instead of modifying the interface on the Javascript side you decided to instead just build a vector of size 1 and extract the id() from the media stream pointer instead.  The commit on Nov 1, 2018 that contained this code (old filename peerconnection.cc) is:

SHA-1: 2e16b9dd229a6c796787d7f0bbe6e9ca57b3ef9e
* Prepare for v0.3.0 (#445)

I believe a goal of your project is to mimic the C++ as much as possible, so ideally we would like to be able to pass in the vector of stream names/id's in the same way that the C++ API's allow.    Note: 
 similar comments apply to AddTransceiver and the webrtc::RtpTransceiverInit struct provided to it. 
 Do you really prefer keeping the APIs as accepting a single MediaStream who's only purpose will be to extract a id/name from it?  Just trying to get an understanding of the direction you would like this go, so we can help as best as possible.

Thanks for your time!
Scott

**Comment by csheely** [comment]
Hi @markandrus ,

Just wondering if you have had a chance to consider Scott's response above?

As he states, we thought our solution better reflected the underlying C++ code, and we thought that was A Good Thing.  But if you could confirm and help us understand why using the MediaStream objects is preferred we could work on an implementation similar to your second suggestion.

Many Thanks!

**Comment by markandrus** [comment]
Hi @sgodin,

> From what I can gather, at one point in time the C++ (webrtc.org) version of PeerConnectionInterface::AddTrack used to take a MediaStream pointer, to allow you associate the track to a particular media stream. So you offered this same interface on the javascript side. Then the webrtc.org code base changed from using a MediaStream pointer to a vector of media stream names. I'm assuming this was done by google along with many other changes for Unified Plan support.

IIRC, the W3C specced JavaScript APIs were still evolving at that time. The JavaScript `addTrack` API was initially specced to accept up to one MediaStream and then specced to accept multiple MediaStream. The webrtc.org C++ changes would have been introduced to better support the specced JavaScript APIs.

> After webrtc.org made that change you modified your code in-step in your project, however, instead of modifying the interface on the Javascript side you decided to instead just build a vector of size 1 and extract the id() from the media stream pointer instead. The commit on Nov 1, 2018 that contained this code (old filename peerconnection.cc) is:

IIRC, that’s because, with the various library code, templates, and macros in this project, it was pretty easy to write JavaScript to C++ converters for fixed argument list methods, but not variable argument methods, such as `addTrack` which takes a repeated MediaStream argument. There is at least one other API in this project that is currently not 100% supported due to this, although I can’t remember it off the top of my head. I’d be very happy to accept fixes for these.

> I believe a goal of your project is to mimic the C++ as much as possible, so ideally we would like to be able to pass in the vector of stream names/id's in the same way that the C++ API's allow.

Actually, the goal of the project is to provide the W3C specced JavaScript APIs, not the webrtc.org C++ APIs. The only place where this project mimics the C++ APIs is in the RTCAudioSource, RTCAudioSink, and related nonstandard APIs which are for testing, experiments, etc.

> Do you really prefer keeping the APIs as accepting a single MediaStream who's only purpose will be to extract a id/name from it? 

It feels a bit funny, but yes—since that is how the W3C specced the JavaScript API (see [here](https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-addtrack)), that is what I think we should do (although ideally we fix the variable argument thing, too).

**Comment by markandrus** [comment]
Thanks for the ping @csheely and sorry for the delay in response @sgodin — I hope my answer clears up how I think this should work (basically mimicking the W3C specced JavaScript APIs as closely as possible, with the caveat that perhaps we could allow constructing a MediaStream with nonstandard dictionary which would allow overriding it’s name; alternatively, if that fails some of the Web Platform Tests, we could expose a nonstandard MediaStreamFactory or something, which just vends MediaStreams with specific names).

One other thing I think it’d be important to test: what happens if multiple MediaStreams with the same name are created? I thought I saw an issue with this in an older webrtc.org checkout.

**Comment by sgodin** [comment]
Thanks for you feedback @markandrus!  I understand your position now.  :)  We will work towards a solution that accepts a vector of media streams in the addTrack API and something that allows setting of a custom MediaStream ID.  Will also check out what it means if the media stream ID is not unique.

Best Regards,
Scott Godin

**Comment by sgodin** [comment]
Changing the relevant API's to accept a vector of MediaStreams seems pretty straight forward.

The other part needed is to allow a custom ID to be assigned to a media stream.  The underlying webrtc.org C++ only supports setting the Stream ID in the MediaStream constructor, so we will need to follow suit in the JS code.  The W3C docs don't say anything about providing a custom stream id to the MediaStream constructor (https://www.w3.org/TR/mediacapture-streams/#dfn-mediastream), so there is no guidance there.

All that being said the **current** Javascript MediaStream constructor allows 4 different ways to construct a MediaStream:
1.  For a Remote MediaStream - accepts PeerConnectionFactory pointer and a MediaStreamInterface pointer
2.  Local MediaStream with a vector of MediaStreamTracks
3.  Local MediaStream with an existing MediaStream pointer.
4.  Local MediaStream with no arguments.

It doesn't make sense to allow passing a custom stream ID to a Remote MediaStream, so we should only consider allowing a custom ID for scenarios 2-4.   I am currently only planning to allow for scenario 4.  Essentially adding a fifth way to construct:

5.  Local MediaStream with a custom ID.

Is there anyone that feels we MUST implement for scenarios 2-3?  Or has a better idea on how to accomplish this?

Thanks,
Scott

**Comment by markandrus** [comment]
@sgodin 

> 1. For a Remote MediaStream - accepts PeerConnectionFactory pointer and a MediaStreamInterface pointer

This should be considered a private API. I have not checked recently, but, IIRC, this API should be impossible to invoke from JavaScript. It should only be invoked from the C++ implementation.

> 2. Local MediaStream with a vector of MediaStreamTracks

This corresponds to the third constructor in the Web IDL [here](https://w3c.github.io/mediacapture-main/#mediastream):

```webidl
[Exposed=Window]
interface MediaStream : EventTarget {
  // ...
  constructor(sequence<MediaStreamTrack> tracks);
  // ...
};
```

> 3. Local MediaStream with an existing MediaStream pointer.

This corresponds to the second constructor in the Web IDL [here](https://w3c.github.io/mediacapture-main/#mediastream):

```webidl
[Exposed=Window]
interface MediaStream : EventTarget {
  // ...
  constructor(MediaStream stream);
  // ...
};
```

> 4. Local MediaStream with no arguments.

This corresponds to the first constructor in the Web IDL [here](https://w3c.github.io/mediacapture-main/#mediastream):

```webidl
[Exposed=Window]
interface MediaStream : EventTarget {
  constructor();
  // ...
};
```

>  I am currently only planning to allow for scenario 4. Essentially adding a fifth way to construct:
>
> 5. Local MediaStream with a custom ID.
>
> Is there anyone that feels we MUST implement for scenarios 2-3? Or has a better idea on how to accomplish this?

I think that's fine—basically changing the first constructor to be

```webidl
[Exposed=Window]
interface MediaStream : EventTarget {
  constructor(optional MediaStreamInit init = {});
  // ...
};
```

I do recommend to have some MediaStreamInit type with an `id` property instead of just a string ID argument you pass in; i.e., something like

```webidl
dictionary MediaStreamInit {
  DOMString id;
};
```

**Comment by sgodin** [comment]
Makes sense to me.  I will work towards that.  Thanks!

**Comment by sgodin** [comment]
Hi Mark,

I have updated the pull request to match what we have been discussing.  Please check it out and let me know if you think it needs further modification.

On a side note, I updated our branch to the latest node-webrtc code last week, and I've noticed that there are now some "npm test" failures.  What's odd is that these don't appear to happen on the GitHub appveyor run.  Perhaps a difference between running on linux vs windows, or maybe related to my node version (I'm using 10.15.2).  Here's the error I'm seeing, both on our branch and with your main develop trunk.  Any idea what is causing that?

Cheers,
Scott
.....
# .enabled on remote MediaStreamTrack
ok 150 enabled can initially be set to false on all MediaStreamTracks
ok 151 enabled can then be set to true on all MediaStreamTracks
ok 152 enabled remains true for all MediaStreamTracks after stopping
ok 153 enabled can still be set on stopped MediaStreamTracks
# connect once
ok 154 connect callback
# connect loop


#
# Fatal error in , line 0
# Check failed: Handle not reset in first callback. See comments on |v8::WeakCallbackInfo|..
#
#
#
#FailureMessage Object: 0000008DFF76D1D0npm ERR! Test failed.  See above for more details.

**Comment by sgodin** [comment]
oh yuck the hash symbols in my log got converted into headings - sorry about that. I think you can still get the gist of the problem though, if you ignore the funky formatting.  :)
