### ISSUE TITLE
Send a pre-encoded h264 stream

### ISSUE THREAD

**Issue by matijagaspar** [node-webrtc/node-webrtc#569]
Hi all,
I know this has been asked before ( #533 ), but after looking at the docs, examples and even a bit of digging trough source, but I could not figure out if it is possible and how. 

The use case, is to be able to send a already encoded file or stream directly to the client without any decoding/encoding on the server side.

The `RTCVideoSource` seems to take I420 frames so, I am not sure I can use it.

Any help would be really appreciated.

**Comment by markandrus** [comment]
I think you would be better served by a proper media server and/or SFU than node-webrtc (which is more like a WebRTC "client", since we're just wrapping the webrtc.org implementation from Chrome). Some projects you could look at (although I'm not sure if they do exactly what you need):

* [versatica/mediasoup](https://github.com/versatica/mediasoup)
* [meetecho/janus-gateway](https://github.com/meetecho/janus-gateway)
* [jitsi/jitsi-videobridge](https://github.com/jitsi/jitsi-videobridge)

I haven't been following the space very closely, so I recommend doing additional research.

**Comment by razvanphp** [comment]
@markandrus can you please give some more insights as to why is this the case? The performance is not expected to be good or are there some incompatibilities?

From my understanding, I420 frames are supposed to be RAW, but the H264 encoded streams would need to send packets (bitstream) along the pipe, right?

This feature would allow many implementations to become possible with boards like RPi which has hardware enconding for 1080p/30fps.

Thank you for this great lib!

**Comment by prkokate-ittiam** [comment]
I am stuck at the same use case. Has anyone been able to do it?
