### ISSUE TITLE
kPlanB only?

### ISSUE THREAD

**Issue by thedracle** [node-webrtc/node-webrtc#615]
It seems like remote track events are not fired except for in kPlanB mode?

See rtc_peer_connection.cc:
```  
if (_jinglePeerConnection->GetConfiguration().sdp_semantics != webrtc::SdpSemantics::kPlanB) {
    return;
  }
```

Is there a specific reason for this since almost everyone has moved to Universal Plan?

**Comment by markandrus** [comment]
Hi @thedracle, in the C++, the if-statement you mention is inside a method, `OnAddTrack`, that we only raise a callback to JavaScript for in the Plan B case. IIRC, this C++ method may also be invoked for the Unified Plan case; however, we do not use it. Instead we use the `OnTrack` flow defined just below it in the same file. Hence the filtering. The “track” event should be supported since 0.1.4 and tested via web-platform-tests (I’m on my phone ATM, and so I cannot easily kink it). Moreover, the default `sdpSemantics` is Unified Plan since 0.4.0. I believe you will find that “track” events are in fact raised. Can you please re-check/try it out?

**Comment by thedracle** [comment]
Thanks for the clarification Mark.

I think the issue was that onAddStream had no body-- which is fine because it's deprecated.

I've generated a wrapper to interface it.
