### ISSUE TITLE
Create a Deno port

### ISSUE THREAD

**Issue by halvardssm** [node-webrtc/node-webrtc#626]
Hi! I am exploring the possibilities of implementing WebRTC in [Deno](https://deno.land/), and I was wondering if there are any plans in supporting Deno in the future? 

If there is no plan for this in the near future, do you mind if I create a port of this repo? How do I need to handle the licences in this case?

Thanks!

**Comment by markandrus** [comment]
Hi @halvardssm, I have no clue what that entails. node-webrtc supports [N-API version 3](https://nodejs.org/api/n-api.html). Does Deno support that? What else is required? If support is not too burdensome we can consider it. Can you sketch out the steps necessary to support Deno?

Regarding licenses, we have [LICENSE.md](https://github.com/node-webrtc/node-webrtc/blob/develop/LICENSE.md) which covers source files. If you distribute node-webrtc binaries, I believe you should also include [THIRD_PARTY_LICENSES.md](https://github.com/node-webrtc/node-webrtc/blob/develop/THIRD_PARTY_LICENSES.md), although IANAL&hellip; Also, regarding licenses, I realize we should probable amend LICENSE.md, considering [test_audio_device_module.h](https://github.com/node-webrtc/node-webrtc/blob/develop/src/webrtc/test_audio_device_module.h) and [test_audio_device_module.c](https://github.com/node-webrtc/node-webrtc/blob/develop/src/webrtc/test_audio_device_module.h) actually come from the webrtc.org code base. Also, THIRD_PARTY_LICENSES.md should really be regenerated, per platform, on every webrtc.org release bump (since dependencies could've changed from release to release).

**Comment by halvardssm** [comment]
@markandrus Thanks for getting back to me! 

So the steps necessary to support Deno is quite cumbersome to be honest, mainly because Deno !== Node. All Node specific methods will have to be translated to Deno and it's not always a direct translation. It's possible a lot of things would need to be ported or be completely rewritten. The easiest would probably be to create a separate folder or repo and rewrite the entire codebase there to support Deno. 

I gladly volunteer to do this since WebRTC is something I would like to understand at a deeper level, and this would be exactly what I would need.

Would you prefer to have a separate repo for Deno support, or to include rewritten code in this repo?

**Comment by markandrus** [comment]
Since it sounds like we cannot (yet?) reuse N-API for Deno (see [here](https://github.com/denoland/deno/issues/237#issuecomment-396239572)), since it sounds like we cannot (yet?) write C plugins for Deno (see [here](https://github.com/denoland/deno/issues/3598)), and since native plugins (still very early) are written in Rust (see [here](https://github.com/denoland/deno/pull/3372)), providing bindings to WebRTC for Deno really sounds like a different project. The only benefit of trying to land it here would be to try and share code between two otherwise different implementations. But if you're writing Rust for the Deno version, I would try to cut ties with most of the C++ here anyway.

It really sounds like a different project at this point, so I suggest you try it out separately. Maybe you can borrow some ideas from this project, though.

**Comment by halvardssm** [comment]
Thank you for the insight! I will probably create a separate project for this then, and use the code from this project as guidance. 

I'll let you know if I succeed in creating a prototype 👍

**Comment by markandrus** [comment]
Thanks, yes I'd be curious :-) GL! Feel free to re-share here.
