### ISSUE TITLE
Can't add specific SDP answer (Chrome can, Chromium can't)

### ISSUE THREAD

**Issue by spartanz51** [node-webrtc/node-webrtc#642]
Hello,

I saw a strange situation with a specific sdp.
node-wrtc can't add my answer to a PeerConnection, it says: 

`Failed to set remote answer sdp: Failed to set remote video description send parameters`

So I tested on the browser, and this SDP answer **is working in Chrome**, but **not working in Chromium**: I have the same error message than using node-wrtc.

Here is the SDP answer I'm trying to add:
https://pastebin.com/raw/ZVjeJS1f

I can't figure out if it's because of plan-b/unified plan compatibility, codec, something wrong in the SDP format, or anything else?

Thanks

![Screenshot_20200628_022522](https://user-images.githubusercontent.com/5300987/85934675-a648d000-b8e6-11ea-8a2b-3c9cd82869ad.png)

**Comment by markandrus** [comment]
Hey, sorry it's unclear where the SDP you shared came from. Did node-webrtc generate it? Did Chromium generate it? What versions of software were you using? For one, the `m=video` line in the SDP looks very strange. It's been a while since I looked at spec, but I don't think it's allowed:

```
m=video 9 UDP/TLS/RTP/SAVP 
```

Note that there are no codecs specified. The line, however, is `a=sendonly`. If this is an answer, one guess I have is that you sent an H.264-only offer to node-webrtc. node-webrtc doesn't support H.264, and maybe this produced an error.

**Comment by spartanz51** [comment]
Thanks for reply. 
I will look into the codecs parts
