### ISSUE TITLE
Question about WebRTC clients

### ISSUE THREAD

**Issue by btsimonh** [node-webrtc/node-webrtc#738]
This repo has a wide range of examples, but I'm struggling with working out if it can do one thing:

I would like to run a webRTC *client* in NodeJS.  
i.e. To be a 'viewer' of a webRTC stream, and to consume the video and audio of that stream in NodeJS.

Am I missing something in the examples, or is this not something it can do?
A simple example which connects to a webRTC session and displays the count of frames received would be great....

**Comment by jzombie** [comment]
Even though this filename says "server" (since it runs on Node) I think this contains examples of the APIs you need.

https://github.com/node-webrtc/node-webrtc-examples/blob/master/examples/record-audio-video-stream/server.js

https://github.com/node-webrtc/node-webrtc-examples/blob/f1d7b9a8483fac1a5b2b48da0dde3b2366b5225f/examples/record-audio-video-stream/server.js#L27-L43
