### ISSUE TITLE
Empty "Examples/peer.html" file

### ISSUE THREAD

**Issue by apiece** [node-webrtc/node-webrtc#96]
When I cloned the project with git, somehow the peer.html file is blank.  However, even after I updated the peer.html with:

<html>
<body></body>

<script src="../dist/wrtc.js"></script>

<script src="peer.js"></script>

</html>

When I run "node examples/bridge.js", the browser still gives me "Not implemented" text on the screen. [Note: I tried latest Chrome and Firefox; and when I ran "npm test", the installation passed all 54 tests.]

**Comment by naps62** [comment]
I just ran into this same issue

The problem is `examples/bridge.js` doesn't actually serve peer.html. The Readme seems unclear about that

But i'm still unable to get this to work.
I tried accessing `peer.html` both via `file:///home/naps62/node-webrtc/examples/peer.html` and also by setting up another node server to serve all the needed files

Either way, having both servers running (`bridge.js` on port 9001, and my `server.js` on port 8000), I get the following output from the browser console:

```
signaling state change:  have-local-offer peer.js:56
signaling state change:  stable peer.js:56
awaiting data channels peer.js:42
ice connection state change:  checking peer.js:60
ice connection state change:  connected peer.js:60
onopen peer.js:93
complete peer.js:34
Uncaught SyntaxError: An invalid or illegal string was specified. peer.js:37
```

notice the error on the last line, instead of the expected `MessageEvent {ports: Array[0], data: "fedcba", source: null, lastEventId: "", origin: ""…}`

**Comment by modeswitch** [comment]
@naps62 Please use the development version of Chrome. I don't think SCTP data channels are enabled in stable yet.

**Comment by apiece** [comment]
Have tried using Chrome dev version (Version 35.0.1862.2 dev). Started the
browser from terminal using "open /Applications/Google\ Chrome.app/ --args
--enable-data-channels".
Same result when trying to reach "peer.html" via port 9001: displaying "Not
Implemented".

**Comment by naps62** [comment]
@apiece the "dev Chrome" tip was for me. Your problem is happening because bridge.js is not actually serving `peer.html` as you might deduce from the readme. `localhost:9001` is just the route to which the data will be sent, not an actual html server

You have to access the file directly, for example from `file:///your/path/to/node-webrtc/examples/peer.html`, or start your own server from that directory

**Comment by modeswitch** [comment]
@apiece to clarify, the websocket server used for signalling runs on 9001. You will need to start a web server to load the HTML part in your browser.

@naps62 also, this now works in Firefox. I'll update the docs.
